import { STEPS } from '@/components/React/Utils/create-listing.steps';

export const stepMapping: Record<string, number> = {
  '1-1': STEPS.PLACE_INFORMATION_PICK_LOCATION,
  '1-4': STEPS.PLACE_INFORMATION_CAPACITY,
  '1-5': STEPS.PLACE_FEATURES_COVER,
  '2-1': STEPS.PLACE_FEATURES_UPLOAD_PHOTOS,
  '2-2': STEPS.PLACE_FEATURES_TITLE,
  '2-3': STEPS.PLACE_FEATURES_DESCRIPTION,
  '2-4': STEPS.PLACE_SETUP_COVER,
  '3-1': STEPS.PLACE_SETUP_DISCOUNT,
  '3-2': STEPS.PLACE_SETUP_DISCOUNT,
};
