export const STEPS = {
  CREATE_LISTING_COVER: 0,
  PLACE_INFORMATION_COVER: 1,
  PLACE_INFORMATION_PLACE_TYPE: 2,
  PLACE_INFORMATION_PICK_LOCATION: 3,
  PLACE_INFORMATION_CONFIRM_LOCATION: 4,
  PLACE_INFORMATION_CAPACITY: 5,
  PLACE_FEATURES_COVER: 6,
  PLACE_FEATURES_AMENITY: 7,
  PLACE_FEATURES_UPLOAD_PHOTOS: 8,
  PLACE_FEATURES_GALLERY: 9,
  PLACE_FEATURES_TITLE: 10,
  PLACE_FEATURES_DESCRIPTION: 11,
  PLACE_SETUP_COVER: 12,
  PLACE_SETUP_PRICING: 13,
  PLACE_SETUP_DISCOUNT: 14,
} as const;

export type StepKey = keyof typeof STEPS;
